export const allProducts = [
  {
    id: 1,
    title: "Dark Side of The Moon",
    artist: "Pink Floyd",
    format: "CD", 
    price: 35990,
    condition: "Nuevo",
    image: "./pink.png",
    badge: "Bestseller",
    genre: "Rock",
  },
  {
    id: 2,
    title: "Abbey Road",
    artist: "The Beatles",
    format: "CD", 
    price: 33990,
    condition: "Nuevo",
    image: "./abbey.png",
    badge: "Clásico",
    genre: "Rock",
  },
  {
    id: 3,
    title: "Thriller",
    artist: "Michael Jackson",
    format: "CD", 
    price: 29990,
    condition: "Nuevo",
    image: "/thriller.jpg",
    badge: null,
    genre: "Pop",
  },
  {
    id: 4,
    title: "Rumours",
    artist: "Fleetwood Mac",
    format: "CD", 
    price: 30990,
    condition: "Nuevo",
    image: "/Rumours.jpg",
    badge: "Nuevo",
    genre: "Rock",
  },
  {
    id: 5,
    title: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    format: "CD", 
    price: 34990,
    condition: "Nuevo",
    image: "/Led.png",
    badge: null,
    genre: "Rock",
  },
  {
    id: 6,
    title: "Meteora",
    artist: "Linkin Park",
    format: "CD", 
    price: 12990,
    condition: "Nuevo",
    image: "/meteora.jpg",
    badge: "Edición Especial",
    genre: "Metal",
  },
  {
    id: 7,
    title: "Back in Black",
    artist: "AC/DC",
    format: "CD", 
    price: 32990,
    condition: "Nuevo",
    image: "/ACDC.png",
    badge: null,
    genre: "Rock",
  },
  {
    id: 8,
    title: "The Chronic",
    artist: "Dr. Dre",
    format: "CD", 
    price: 38990,
    condition: "Nuevo",
    image: "/dre.jpg",
    badge: null,
    genre: "Rap",
  },
  {
    id: 9,
    title: "Blue Lines",
    artist: "Massive Attack",
    format: "CD", 
    price: 28990,
    condition: "Nuevo",
    image: "/Blue.jpg",
    badge: null,
    genre: "Jazz",
  },
  {
    id: 10,
    title: "Nevermind",
    artist: "Nirvana",
    format: "CD", 
    price: 34490,
    condition: "Nuevo",
    image: "/Never.jpg",
    badge: "Grunge Clásico",
    genre: "Grunge",
  },
  {
    id: 11,
    title: "Kind of Blue",
    artist: "Miles Davis",
    format: "CD", 
    price: 29490,
    condition: "Nuevo",
    image: "/Kind.png",
    badge: null,
    genre: "Jazz",
  },
  {
    id: 12,
    title: "Vol.3: The Subliminal Verse",
    artist: "Slipknot",
    format: "CD",
    price: 27990,
    condition: "Nuevo",
    image: "/verse.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 13,
    title: "Master of Puppets",
    artist: "Metallica",
    format: "CD", 
    price: 36990,
    condition: "Nuevo",
    image: "/master.png",
    badge: null,
    genre: "Metal",
  },
  {
    id: 14,
    title: "Dookie",
    artist: "Green Day",
    format: "CD", 
    price: 26990,
    condition: "Nuevo",
    image: "/dook.jpg",
    badge: null,
    genre: "Punk",
  },
  {
    id: 15,
    title: "London Calling",
    artist: "The Clash",
    format: "CD Doble",
    price: 42990,
    condition: "Nuevo",
    image: "/clash.png",
    badge: null,
    genre: "Punk",
  },
  {
    id: 16,
    title: "Bad",
    artist: "Michael Jackson",
    format: "CD",
    price: 12990,
    condition: "Nuevo",
    image: "/bad.png",
    badge: null,
    genre: "Pop",
  },
  {
    id: 17,
    title: "Three Cheers For Sweet Revenge",
    artist: "My Chemical Romance",
    format: "CD", 
    price: 19990,
    condition: "Nuevo",
    image: "/mych.jpg",
    badge: "Popular",
    genre: "Emo",
  },
  {
    id: 18,
    title: "To Pimp a Butterfly",
    artist: "Kendrick Lamar",
    format: "CD", 
    price: 43990,
    condition: "Nuevo",
    image: "/topimp.jpg",
    badge: null,
    genre: "Rap",
  },
  {
    id: 19,
    title: "Un Verano Sin Ti",
    artist: "Bad Bunny",
    format: "CD", 
    price: 39990,
    condition: "Nuevo",
    image: "/weamala.jpg",
    badge: "Popular",
    genre: "Reggaetón",
  },
  {
    id: 20,
    title: "Barrio Fino",
    artist: "Daddy Yankee",
    format: "CD",
    price: 11990,
    condition: "Nuevo",
    image: "/daddy.jpg",
    badge: null,
    genre: "Reggaetón",
  },
  {
    id: 21,
    title: "Astroworld",
    artist: "Travis Scott",
    format: "CD", 
    price: 37990,
    condition: "Nuevo",
    image: "/scott.jpg",
    badge: "Bestseller",
    genre: "Trap",
  },
  {
    id: 22,
    title: "Die Lit",
    artist: "Playboi Carti",
    format: "CD", 
    price: 34990,
    condition: "Nuevo",
    image: "/play.png",
    badge: null,
    genre: "Trap",
  },
  {
    id: 23,
    title: "The Black Album",
    artist: "Metallica",
    format: "CD", 
    price: 35990,
    condition: "Nuevo",
    image: "/black.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 24,
    title: "Paranoid",
    artist: "Black Sabbath",
    format: "CD",
    price: 33990,
    condition: "Nuevo",
    image: "/paranoid.png",
    badge: "Clásico",
    genre: "Metal",
  },
  {
    id: 25,
    title: "American Idiot",
    artist: "Green Day",
    format: "CD", 
    price: 32490,
    condition: "Nuevo",
    image: "/american.png",
    badge: null,
    genre: "Punk",
  },
  {
    id: 26,
    title: "Never Mind the Bollocks",
    artist: "Sex Pistols",
    format: "CD", 
    price: 30990,
    condition: "Nuevo",
    image: "/Sex.jpg",
    badge: null,
    genre: "Punk",
  },
  {
    id: 27,
    title: "Born Under a Bad Sign",
    artist: "Albert King",
    format: "CD", 
    price: 28490,
    condition: "Nuevo",
    image: "alber.png",
    badge: null,
    genre: "Blues",
  },
  {
    id: 28,
    title: "The Thrill Is Gone",
    artist: "B.B. King",
    format: "CD",
    price: 10990,
    condition: "Nuevo",
    image: "/gone.jpg",
    badge: null,
    genre: "Blues",
  },
  {
    id: 29,
    title: "A Love Supreme",
    artist: "John Coltrane",
    format: "CD", 
    price: 29990,
    condition: "Nuevo",
    image: "/supre.jpg",
    badge: "Clásico",
    genre: "Jazz",
  },
  {
    id: 30,
    title: "Time Out",
    artist: "Dave Brubeck Quartet",
    format: "CD", 
    price: 29490,
    condition: "Nuevo",
    image: "/time.jpg",
    badge: null,
    genre: "Jazz",
  },
  {
    id: 31,
    title: "Peace Sells",
    artist: "Megadeth",
    format: "CD", 
    price: 26990,
    condition: "Nuevo",
    image: "/deth.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 32,
    title: "Infinite",
    artist: "Stratovarius",
    format: "CD", 
    price: 28490,
    condition: "Nuevo",
    image: "/infi.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 33,
    title: "The Black Parade",
    artist: "My Chemical Romance",
    format: "CD", 
    price: 34490,
    condition: "Nuevo",
    image: "/parade.jpg",
    badge: "Emo Clásico",
    genre: "Emo",
  },
  {
    id: 34,
    title: "Tell All Your Friends",
    artist: "Taking Back Sunday",
    format: "CD", 
    price: 30990,
    condition: "Nuevo",
    image: "/tella.jpg",
    badge: null,
    genre: "Emo",
  },
  {
    id: 35,
    title: "Maggot Brain",
    artist: "Funkadelic",
    format: "CD", 
    price: 31990,
    condition: "Nuevo",
    image: "/margo.jpg",
    badge: null,
    genre: "Funk",
  },
  {
    id: 36,
    title: "Hot Buttered Soul",
    artist: "Isaac Hayes",
    format: "CD", 
    price: 29990,
    condition: "Nuevo",
    image: "/pelon.jpg",
    badge: null,
    genre: "Funk",
  },
  {
    id: 37,
    title: "In the Hands of the Inevitable",
    artist: "The Skatalites",
    format: "CD", 
    price: 27990,
    condition: "Nuevo",
    image: "/hands.jpg",
    badge: null,
    genre: "Ska",
  },
  {
    id: 38,
    title: "Everything Goes Numb",
    artist: "Streetlight Manifesto",
    format: "CD", 
    price: 29490,
    condition: "Nuevo",
    image: "/every.jpg",
    badge: null,
    genre: "Ska",
  },
  {
    id: 39,
    title: "The Queen Is Dead",
    artist: "The Smiths",
    format: "CD", 
    price: 32490,
    condition: "Nuevo",
    image: "queen.png",
    badge: "Bestseller",
    genre: "rock ",
  },
  {
    id: 40,
    title: "Exodus",
    artist: "Bob Marley & The Wailers",
    format: "CD", 
    price: 30990,
    condition: "Nuevo",
    image: "/exo.jpg",
    badge: null,
    genre: "Reggae",
  },
  {
    id: 41,
    title: "City Of Evil",
    artist: "Avenged Sevenfold",
    format: "CD",
    price: 13990,
    condition: "Nuevo",
    image: "/city.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 42,
    title: "Greatest Hits",
    artist: "Queen",
    format: "CD",
    price: 14990,
    condition: "Nuevo",
    image: "/great.jpg",
    badge: "Clásico",
    genre: "Rock",
  },
  {
    id: 43,
    title: "Simple Plan",
    artist: "Simple Plan",
    format: "CD",
    price: 18990,
    condition: "Nuevo",
    image: "/simpl.jpg",
    badge: "Popular",
    genre: "Punk",
  },
  {
    id: 44,
    title: "Born Pink",
    artist: "BLACKPINK",
    format: "CD",
    price: 17990,
    condition: "Nuevo",
    image: "/born.jpg",
    badge: null,
    genre: "Pop",
  },
  {
    id: 45,
    title: "The Poison",
    artist: "Bullet Fom My Valentine",
    format: "CD",
    price: 9990,
    condition: "Nuevo",
    image: "/poison.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 46,
    title: "Follow The Leader",
    artist: "Korn",
    format: "CD", 
    price: 24990,
    condition: "Nuevo",
    image: "/korn.jpg",
    badge: null,
    genre: "Metal",
  },
  {
    id: 47,
    title: "In Utero",
    artist: "Nirvana",
    format: "CD", 
    price: 33490,
    condition: "Nuevo",
    image: "/ute.jpg",
    badge: null,
    genre: "Grunge",
  },
  {
    id: 48,
    title: "Ten",
    artist: "Pearl Jam",
    format: "CD", 
    price: 34990,
    condition: "Nuevo",
    image: "/pearl.jpg",
    badge: null,
    genre: "Grunge",
  }
]
